name = "zendo-backend"
compatibility_date = "2025-06-06"
compatibility_flags = ["nodejs_compat"]

main = "index.js"

[observability.logs]
enabled = true

analytics_engine_datasets = [
  { binding = "ANALYTICS_ENGINE", dataset = "analytics_event" }
]